# Generated by Django 4.2.4 on 2023-08-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=10)),
                ("car_type", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=15, null=True)),
                ("year", models.IntegerField(default=0)),
                ("km", models.IntegerField(default=0)),
                ("test_date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("product_name", models.CharField(max_length=20)),
                ("description", models.TextField(max_length=500)),
                ("category", models.CharField(max_length=20)),
            ],
        ),
    ]
