# Generated by Django 4.2.4 on 2023-08-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carcare", "0002_car_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="brand",
            field=models.CharField(default="default", max_length=15),
        ),
    ]
