# Generated by Django 4.2.4 on 2023-08-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carcare", "0006_wheelchange_service_repair_insurance"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="plate_number",
            field=models.IntegerField(max_length=8, null=True),
        ),
        migrations.CreateModel(
            name="Fuel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuel_type", models.CharField(max_length=20, null=True)),
                ("fuel_amount", models.IntegerField(default=0, null=True)),
                ("station_name", models.CharField(max_length=20, null=True)),
                ("km_per_tank", models.IntegerField(default=0, null=True)),
                ("price_per_gallon", models.IntegerField(default=0, null=True)),
                ("fuel_overall_price", models.IntegerField(default=0, null=True)),
                ("fuel_date", models.DateField(null=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="carcare.car"
                    ),
                ),
            ],
        ),
    ]
