# Generated by Django 4.2.4 on 2023-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carcare", "0007_car_plate_number_fuel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="plate_number",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
